[package]
name = "libDF-swift"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deep_filter = { features = ["transforms"], path = "../libDF" }

[lib]
name = "mathwiz"
crate-type = [ "staticlib" ]
